PascalWeb/Controllers/SubscriptionController.cs
using PascalWeb.Additional.Auth;
using PascalWeb.DB;
using PascalWeb.DB.PageModels;
using PascalWeb.DB.PageModels.Specific;
using PascalWeb.DB.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PascalWeb.Controllers
{
    [DynamicAuthorizeAttribute]
    public class SubscriptionController : ControllerBase
    {
        UnitOfWork unitOfWork = new UnitOfWork();

        public ActionResult ShowSubscription()
        {
            var userID = getCurrentUserID();

            var programSubscriptionList = unitOfWork.SubscriptionProgramRepository.Get(filter: obj => obj.UserID == userID && obj.Existed, orderBy: q => q.OrderByDescending(x => x.CreationDate),
                includeProperties: "Program");
            var blogSubscriptionList = unitOfWork.SubscriptionBlogRepository.Get(filter: obj => obj.UserID == userID && obj.Existed, orderBy: q => q.OrderByDescending(x => x.CreationDate),
                includeProperties: "Blog");

            SubscriptionProfileModel model = new SubscriptionProfileModel(programSubscriptionList, blogSubscriptionList);

            // add remaining programs for subscription
            var subscribedProgramIDList = programSubscriptionList.Select(x => x.ProgramID);
            var remainProgramList = unitOfWork.ProgramRepository.Get(filter: obj => !subscribedProgramIDList.Contains(obj.ID), orderBy: q => q.OrderByDescending(x => x.Name));
            for (int i = 0; i < remainProgramList.Count(); i++)
                model.SubscriptionProgramList.Add(new SubscriptionProfileModel.SubscriptionModel(remainProgramList.ElementAt(i)));
            
            // add remaining blogs for subscription
            var subscribedBlogIDList = blogSubscriptionList.Select(x => x.BlogID);
            var remainBlogList = unitOfWork.BlogRepository.Get(filter: obj => !subscribedBlogIDList.Contains(obj.ID), orderBy: q => q.OrderByDescending(x => x.Name));
            for (int i = 0; i < remainBlogList.Count(); i++)
                model.SubscriptionBlogList.Add(new SubscriptionProfileModel.SubscriptionModel(remainBlogList.ElementAt(i)));

                return PartialOrFullView(model: model);
        }

        /// <summary>
        /// subscribe to blog
        /// </summary>
        [HttpGet]
        public ActionResult BlogSubscribe(int blogID, bool on, bool changeToSubscibtionIndication = false)
        {
            long? userID = getCurrentUserID();
            if (!userID.HasValue)
                PartialOrFullView("_updateBlogSubscribeButton", model: on);

            SubscriptionController.blogSubscribe(unitOfWork, userID, blogID, on);
            SubscriptionButtonModel model = new SubscriptionButtonModel(blogID, on, changeToSubscibtionIndication);
            return PartialOrFullView("_updateBlogSubscribeButton", model: model);
        }

        /// <summary>
        /// subscribe to program
        /// </summary>
        [HttpGet]
        public ActionResult ProgramSubscribe(int programID, bool on, bool changeToSubscibtionIndication = false)
        {
            long? userID = getCurrentUserID();
            if (!userID.HasValue)
                PartialOrFullView("_updateProgramSubscribeButton", model: on);

            SubscriptionController.programSubscribe(unitOfWork, userID, programID, on);
            SubscriptionButtonModel model = new SubscriptionButtonModel(programID, on, changeToSubscibtionIndication);
            return PartialOrFullView("_updateProgramSubscribeButton", model: model);
        }

        public static bool? blogSubscribe(UnitOfWork unitOfWork, long? userID,int blogID, bool on)
        {
            SubscriptionBlog subcription = unitOfWork.SubscriptionBlogRepository.Get(filter: obj => obj.BlogID == blogID && obj.UserID == userID).FirstOrDefault();

            if (subcription == null)
            {
                subcription = new SubscriptionBlog();
                subcription.CreationDate = DateTime.Now;
                subcription.BlogID = blogID;
                subcription.UserID = userID.Value;
                subcription.Existed = on;
                unitOfWork.SubscriptionBlogRepository.Insert(subcription);
            }
            subcription.Existed = on;

            unitOfWork.Save();
            return !on;
        }

        public static bool? programSubscribe(UnitOfWork unitOfWork, long? userID, int programID, bool on)
        {
            SubscriptionProgram subcription = unitOfWork.SubscriptionProgramRepository.Get(filter: obj => obj.ProgramID == programID && obj.UserID == userID).FirstOrDefault();

            if (subcription == null)
            {
                subcription = new SubscriptionProgram();
                subcription.CreationDate = DateTime.Now;
                subcription.ProgramID = programID;
                subcription.UserID = userID.Value;
                subcription.Existed = on;
                unitOfWork.SubscriptionProgramRepository.Insert(subcription);
            }
            subcription.Existed = on;

            unitOfWork.Save();
            return !on;
        }

        /// <summary>
        /// check whether user is subscribed to blog
        /// </summary>
        /// <param name="unitOfWork"></param>
        /// <param name="userID"></param>
        /// <param name="blogID"></param>
        /// <returns></returns>
        public static bool? checkBlogSuscription(UnitOfWork unitOfWork, long? userID, int blogID)
        {
            if (!userID.HasValue)
                return null;

            // #TODO
            SubscriptionBlog subcription = unitOfWork.SubscriptionBlogRepository.Get(filter: obj => obj.BlogID == blogID && obj.UserID == userID).FirstOrDefault();
            if (subcription == null || !subcription.Existed)
            {
                return false;
            }
            else
                return true;
        }

        /// <summary>
        /// check whether user is subscribed to program
        /// </summary>
        /// <param name="programID"></param>
        /// <returns></returns>
        public static bool? checkProgramSuscription(UnitOfWork unitOfWork, long? userID, int programID)
        {
            if (!userID.HasValue)
                return null;

            // #TODO
            SubscriptionProgram subcription = unitOfWork.SubscriptionProgramRepository.Get(filter: obj => obj.ProgramID == programID && obj.UserID == userID).FirstOrDefault();
            if (subcription == null || !subcription.Existed)
            {
                return false;
            }
            else
                return true;
        }
    }
}

PascalWeb/Views/Subscription/ShowSubscription.cshtml
@model PascalWeb.DB.PageModels.SubscriptionProfileModel


@Styles.Render("~/Content/RoxieTheme/css/style-custom-program.css")
@Styles.Render("~/Content/RoxieTheme/css/style-custom-podcast.css")

@Html.Partial("_PageTittle", "PascalFM - Мои подписки")
@Html.Partial("_HeadNavigation", 4)

<div class="l-content">
    <div class="container">
        <div class="container-fluid col-md-12 col-lg-12 ">
            <h1 class="b-title-h1 b-title-h1-center b-title-h1_fs22">Мои Подписки</h1>
            @Html.ActionLink("Назад к профилю", "Index", "Profile", null, htmlAttributes: new { @class = "btn btn-small btn-primary pull-right", withpjax = "withpjax" })
        </div>
        @if (Model != null)
        {
            <div class="container-fluid col-md-6 col-lg-6 ">
                <div class="b-list-programs table-responsive">
                    <h1 class="b-title-h1_fs22 b-main_color" style="text-align:center">Подписки на подкасты</h1>
                    <br />
                    <table class="b-list-programs__item table">
                        @for (int i = 0; i < Model.SubscriptionProgramList.Count(); i++)
                        {
                            var programSubItem = @Model.SubscriptionProgramList[i];
                            <tr class="b-list-program">
                                <td>
@*                                    <img src="@programSubItem.ImagePath" width="50" height="50"/>*@
                                    @if (!string.IsNullOrEmpty(programSubItem.ImagePath))
                                    {
                                        @:<img src="@programSubItem.ImagePath" alt="" class="" style="min-width:50px">
                                    } else
                                    {
                                        @:<img alt="" class="b-main_image_default_program_small " style="min-width:50px">
                                    }
                                </td>
                                <td>
                                    @Html.ActionLink(programSubItem.ObjectName, "Details", "Program", routeValues: new { id = programSubItem.SubsciptionObjectID },
                                        htmlAttributes: new { @class = "b-main_color", withpjax = "withpjax"})
                                </td>
                                <td>
                                    <div class="pull-right" id="@("_updateProgramSubscribeButton" + programSubItem.SubsciptionObjectID.ToString())">
                                        @Html.Partial("_updateProgramSubscribeButton", new PascalWeb.DB.PageModels.Specific.SubscriptionButtonModel(programSubItem.SubsciptionObjectID, programSubItem.Existed, false))
                                    </div>
                                </td>
                            </tr>
                        }
                    </table>
                </div>        
            </div>
            
                
             <div class="container-fluid col-md-6 col-lg-6 ">
                <div class="b-list-programs table-responsive">
                    <h1 class="b-title-h1_fs22 b-main_color" style="text-align:center">Подписки на блоги</h1>
                    <br />
                    <table class="b-list-programs__item table">
                        @for (int i = 0; i < Model.SubscriptionBlogList.Count(); i++)
                        {
                            var blogSubItem = @Model.SubscriptionBlogList[i];
                            <tr class="b-list-program">
                                <td>
                                  @*  <img src="@blogSubItem.ImagePath" width="50" height="50"/>*@
                                    @if (!string.IsNullOrEmpty(blogSubItem.ImagePath))
                                    {
                                        @:<img src="@blogSubItem.ImagePath" alt="" class="b-rating__list__item__img" style="min-width:50px">
                                    } else
                                    {
                                        @:<img alt="" class="b-main_image_default_blog_small b-rating__list__item__img" style="min-width:50px">
                                    }
                                </td>
                                <td>
                                    @Html.ActionLink(blogSubItem.ObjectName, "Index", "BlogRecord", routeValues: new { blogid = blogSubItem.SubsciptionObjectID },
                                        htmlAttributes: new { @class = "b-main_color", withpjax = "withpjax"})
                                </td>
                                <td>
                                    <div id="@("_updateBlogSubscribeButton" + blogSubItem.SubsciptionObjectID.ToString())">
                                        @Html.Partial("_updateBlogSubscribeButton", new PascalWeb.DB.PageModels.Specific.SubscriptionButtonModel(blogSubItem.SubsciptionObjectID, blogSubItem.Existed, false))
                                    </div>
                                </td>
                            </tr>
                        }
                    </table>
                </div>        
            </div>
        }
    </div>
</div>

PascalWeb/Views/Subscription/_updateBlogSubscribeButton.cshtml
@model PascalWeb.DB.PageModels.Specific.SubscriptionButtonModel

@if(Model.Existed.HasValue)
{
    if (Model.Existed.Value && Model.ChangeToSubscibtionIndication)
    {
        <button type="submit" class="b-blck b-blck_bg-green b-blck_subscribe pull-right" style = "margin-bottom:0px;width:240px;background-color:gray" disabled="disabled">Вы подписаны на блог</button>
    } 
    else
    {
        using (Ajax.BeginForm("BlogSubscribe", "Subscription", new { blogID = Model.ObjectID, on = !Model.Existed.Value }, new AjaxOptions
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "_updateBlogSubscribeButton" + Model.ObjectID,
            LoadingElementId = "loadLayout"
        }))
        {
            if (Model.Existed.Value)
            {
                <button type="submit" class="b-blck b-blck_bg-green b-blck_subscribe pull-right" style = "margin-bottom:0px;width:240px;background-color:gray">Отписаться от блога</button>

            }
            else
            {
                <button type="submit" class="b-blck b-blck_bg-green b-blck_subscribe pull-right" style = "margin-bottom:0px;width:240px">Подписаться на блог</button>
            }
        }
    } 
}

PascalWeb/Views/Subscription/_updateProgramSubscribeButton.cshtml
@model PascalWeb.DB.PageModels.Specific.SubscriptionButtonModel


@if(Model.Existed.HasValue)
{
    if (Model.Existed.Value && Model.ChangeToSubscibtionIndication)
    {
        <button type="submit" class="b-blck b-blck_bg-green b-blck_subscribe" style = "margin-bottom:0px;width:240px;background-color:gray" disabled="disabled">Вы подписаны</button>
    } 
    else
    {
        using (Ajax.BeginForm("ProgramSubscribe", "Subscription", new { programID = Model.ObjectID, on = !Model.Existed.Value }, new AjaxOptions
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "_updateProgramSubscribeButton" + Model.ObjectID,
            LoadingElementId = "loadLayout"
        }))
        {
            if (Model.Existed.Value)
            {
                <button type="submit" class="b-blck b-blck_bg-green b-blck_subscribe" style = "margin-bottom:0px;width:240px;background-color:gray">Отписаться</button>
            }
            else
            {
                <button type="submit" class="b-blck b-blck_bg-green b-blck_subscribe" style = "margin-bottom:0px;width:240px">Подписаться</button>  
            }
        }
    }
}