PascalWeb/Controllers/AudioPlayerController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PascalWeb.DB;
using PascalWeb.DB.PageModels;
using PascalWeb.Additional.Auth;
using PascalWeb.Additional;
using PascalWeb.DB.Repositories;
using PascalWeb.Additional.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using PascalWeb.Additional.Algorithms;

namespace PascalWeb.Controllers
{
    [DynamicAuthorizeAttribute]
    public class AudioPlayerController : ControllerBase
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        // http://stackoverflow.com/questions/23807535/azure-download-blob-filestream-memorystream

        /// <summary>
        /// 
        /// </summary>
        /// <param name="programEditionID"></param>
        /// <returns></returns>
        public ActionResult  Download(long programEditionID)
        {
            try
            {
                //cStorageManager.setSpecialSettings();
                var programEdition = unitOfWork.ProgramEditionRepository.GetOneItem(obj => obj.ID == programEditionID, "Content");
                if (programEdition != null && programEdition.Content != null)
                {
                    string editionTitle = Transliteration.translite(programEdition.EditionTittle);
                    editionTitle = editionTitle.Replace(" ", "_");
                    string downloadLink = cStorageManager.getDownloadLink(programEdition.Content.AbsoluteFileUri, editionTitle);
                    ProgramEditionManagment.addToProgramEditionCounters(unitOfWork, Request, programEditionID, null, null, null, true);
                    return Redirect(downloadLink);
                }
                else
                {
                    return null;
                }
            }
            catch (Exception exc)
            {
                PascalLogging.WriteErrorMessage("AudioPlayerController", "Download", exc.Message);
                return null;
            }
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="programEditionID"></param>
        /// <returns></returns>
        public string Listen(long id)
        {
            try
            {
                //cStorageManager.setSpecialSettings();
                var programEdition = unitOfWork.ProgramEditionRepository.GetOneItem(obj => obj.ID == id, "Content");
                if (programEdition != null && programEdition.Content != null)
                {
                    return programEdition.Content.AbsoluteFileUri;
                }
                else
                {
                    return null;
                }
            }
            catch (Exception exc)
            {
                PascalLogging.WriteErrorMessage("AudioPlayerController", "Listen", exc.Message);
                return "";
            }
        }
    }
}

PascalWeb/Controllers/ProgramEditionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.WindowsAzure.Storage.Blob;
using PascalWeb.Additional.Auth;
using PascalWeb.Additional.Storage;
using PascalWeb.DB;
using PascalWeb.DB.AuxiliaryModels;
using PascalWeb.DB.PageModels;
using PascalWeb.DB.Repositories;
using PascalWeb.Additional;
using PascalWeb.Additional.FileProcessing;
using PascalWeb.DB.Enumerators;
using PascalWeb.Additional.Audio;

namespace PascalWeb.Controllers
{
    [DynamicAuthorizeAttribute]
    public class ProgramEditionController : ControllerBase
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        private PascalDBEntities context = new PascalDBEntities();

        //
        // GET: /ProgramEdition/Details/5

        public ActionResult Details(long id = 0)
        {
            ProgramEdition programEdition = unitOfWork.ProgramEditionRepository.GetOneItem(obj => obj.ID == id, "Content, Program, ProgramEditionText");
            if (programEdition == null)
            {
                return HttpNotFound();
            }
            Session["SelectedProgramEditionID"] = id;

            ProgramEditionPageView model = new ProgramEditionPageView();
            model.ProgramEdition = programEdition;
            model.Comments = getProgramEditionComments(null, 0, ConstantSettings.CommentBatchNumber);
            model.Recommendation = getRecommendationList(unitOfWork, programEdition.Recommendations);

            List<AudioTransferData> audioData = AudioManager.setPlayList(model.Recommendation.LastProgramEditions);
            audioData.Insert(0, new AudioTransferData(programEdition));

            Session[AudioManager.PLAYLIST_SESSION_KEY] = audioData;
           // Session[AudioManager.PLAYLIST_SESSION_KEY] = audioData;

   
            addToProgramEditionCounters(false, true, false, false);

            return PartialOrFullView(model: model);
        }

        private LastProgramEditionPageModel getRecommendationList(UnitOfWork unitOfWork, string recommendationString)
        {
            var peList = new List<ProgramEdition>();
            List<long> editionIDList = Serialization.stringToLongList(recommendationString);
            for (int i = 0; i < 4 && i < editionIDList.Count; i++)
            {
                long editionID = editionIDList[i];
                ProgramEdition pe = unitOfWork.ProgramEditionRepository.GetOneItem(filter: obj => obj.ID == editionID, includeProperties: "Content, Program");
                peList.Add(pe);
            }
            var model = LastProgramEditionPageModel.getLastProgramEditionModel(peList);

            return model;
        }

        // ----------------------------------------------------------------------------------------------
        // COMMENTS
        // ----------------------------------------------------------------------------------------------



        [HttpPost]
        public ActionResult GetMoreProgramEditionComments(int? pageNumber)
        {
            var page = pageNumber.HasValue ? pageNumber.Value : 0;

            int skipNumber = (page) * ConstantSettings.CommentBatchNumber;
            var model = getProgramEditionComments(null, skipNumber, ConstantSettings.CommentBatchNumber).CommentsList;
            return base.PartialView("_ViewCommentList", model);
        }

        /// <summary>
        /// get n comments
        /// </summary>
        /// <param name="programEditionID"></param>
        /// <param name="lastCommentID"></param>
        /// <returns></returns>
        private CommentBoxModel getProgramEditionComments(int? lastCommentID, int skipSize, int batchSize)
        {
            long? currentUserID = getCurrentUserID();

            string roleName = getRoleName();
            bool alwaysCanEdit = ((roleName == eUserRoles.admin.ToString()) || (roleName == eUserRoles.superadmin.ToString()) ||
                            (roleName == eUserRoles.moderator.ToString()) || (roleName == eUserRoles.editor.ToString()));
            long? programEditionID = null;
            if (Session["SelectedProgramEditionID"] != null)
                programEditionID = (long)Session["SelectedProgramEditionID"];

            var programEditionComments = unitOfWork.CommentProgramEditionRepository.Get(filter: obj => obj.ProgramEditionID == programEditionID && !obj.Deleted, 
                includeProperties: "UserAuth").Skip(skipSize).Take(batchSize);
            List<CommonCommentViewModel> comments = new List<CommonCommentViewModel>();
            for (int i = 0; i < programEditionComments.Count(); i++)
            {
                var comment = programEditionComments.ElementAt(i);
                CommonCommentViewModel _comment = new CommonCommentViewModel(comment.ID,
                                                                    comment.UserAuth,
                                                                    comment.CreationDate,
                                                                    comment.Comment,
                                                                    (alwaysCanEdit || (currentUserID == comment.UserAuth.ID)), 
                                                                    "ProgramEdition");
                comments.Add(_comment);
            }

            //int wholeCommentNumber = unitOfWork.CommentProgramEditionRepository.Get(obj => obj.ProgramEditionID == programEditionID && !obj.Deleted).Count();
            //User.Identity.
      
            CommentBoxModel model = new CommentBoxModel(comments, new int?(), new KeyValuePair<string, string>("GetMoreProgramEditionComments", "ProgramEdition"), unitOfWork.UserManagment.getUserLogoByID(getCurrentUserID()));
            return model;
        }

        /// <summary>
        /// Add comment
        /// </summary>
        /// <param name="commentText"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AddComment(string commentText)
        {
            var programEditionID = (long)Session["SelectedProgramEditionID"];
            if (!string.IsNullOrWhiteSpace(commentText))
            {
                CommentProgramEdition comment = new CommentProgramEdition();
                comment.Comment = commentText;
                comment.CreationDate = DateTime.Now;
                comment.ProgramEditionID = programEditionID;
                comment.UserID = getCurrentUserID().Value;

                unitOfWork.CommentProgramEditionRepository.Insert(comment);
                unitOfWork.Save();
                addToProgramEditionCounters(true, false, false, false);
            }

            CommentBoxModel model = getProgramEditionComments(null, 0, ConstantSettings.CommentBatchNumber);

            return base.PartialView("_ViewCommentBox", model);
        }

        /// <summary>
        /// Delete comment
        /// </summary>
        /// <param name="commentID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult DeleteComment(long commentID)
        {
            var comment = unitOfWork.CommentProgramEditionRepository.GetByID(commentID);
            unitOfWork.CommentProgramEditionRepository.Delete(comment);
            unitOfWork.Save();
            addToProgramEditionCounters(true, false, false, false);

           // long ProgramEditionID = (long)Session["SelectedProgramEditionID"];
            CommentBoxModel model = getProgramEditionComments(null, 0, ConstantSettings.CommentBatchNumber);
            return base.PartialView("_ViewCommentBox", model);
        }

        /// <summary>
        /// Delete comment
        /// </summary>
        /// <param name="commentID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult EditComment(long commentID)
        {
            var comment = unitOfWork.CommentProgramEditionRepository.GetByID(commentID);
           // unitOfWork.CommentProgramEditionRepository.Delete(comment);
            unitOfWork.Save();

            //long ProgramEditionID = (long)Session["SelectedProgramEditionID"];
            CommentBoxModel model = getProgramEditionComments(null, 0, ConstantSettings.CommentBatchNumber);
            return base.PartialView("_ViewCommentBox", model);
        }


        // ----------------------------------------------------------------------------------------------
        //  Counters
        // ----------------------------------------------------------------------------------------------
        private bool addToProgramEditionCounters(bool? updateCommentCounter, bool? addToViewedCounter, bool? addToListenedCounter, bool? addToDownloadCounter)
        {
            try
            {
                var programEditionID = (long)Session["SelectedProgramEditionID"];
                return ProgramEditionManagment.addToProgramEditionCounters(unitOfWork, Request, programEditionID, updateCommentCounter, addToViewedCounter, addToListenedCounter, addToDownloadCounter);
            }
            catch (Exception)
            {
                // logging
                return false;
            }
        }


        // ----------------------------------------------------------------------------------------------
        // 
        // ----------------------------------------------------------------------------------------------


        //
        // GET: /ProgramEdition/Create

        public ActionResult Create(int programID)
        {
            ViewBag.ProgramID = new SelectList(unitOfWork.getContext().Program, "ID", "Name");

            // clear session data
            Session[TagController.SESSION_MANAGMENT_TAGS] = null;
            Session[ProfileController.SESSION_PROGRAM_AUTHORS] = null;

            // for dropdownList
            var programsList = unitOfWork.ProgramRepository.Get(

PascalWeb/Controllers/SearchController.cs
using PascalWeb.DB.PageModels;
using PascalWeb.DB.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PascalWeb.Controllers
{
    public class SearchController : ControllerBase
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        //
        // GET: /Search/
        [HttpGet]
        public ActionResult Index(SearchModel modelData)
        {
            searchIt(modelData);
            return PartialOrFullView(model: modelData);
        }

        [HttpGet]
        public ActionResult PartialSearch(SearchModel modelData)
        {
            searchIt(modelData);
            return base.PartialView("_resultItems", model: modelData);
        }

        [HttpGet]
        public ActionResult Search(string query, SearchResult.SearchResultType searchType = SearchResult.SearchResultType.All)
        {
            SearchModel model = new SearchModel();
            model.Query = query;
            model.IsHashTag = true;
            model.IsSearchInPrograms = true;
            model.SearchType = searchType;
            return Index(model);
        }

        private List<string> getTagNameList(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
                return new List<string>();
            var array = query.Split(new char[] { ' ' });
            var result = (from word in array
                         where string.IsNullOrWhiteSpace(word) == false
                         select word.Replace('#', ' ').Trim().ToLower()).ToList<string>();

            return result;
        }


        private void searchIt(SearchModel model)
        {
            model.SearchResultList = new List<SearchResult>();
            //if (model.IsHashTag)
            {
                List<string> tagIDList_lowerCase = getTagNameList(model.Query);
                if (string.IsNullOrEmpty(model.Query))
                    return;

                searchInProgramEditions(ref model, tagIDList_lowerCase);
                searchInBlogRecords(ref model, tagIDList_lowerCase);

                model.SearchResultList = model.SearchResultList.OrderByDescending(q => q.PublishTime).ToList();
            }
        }

        private void searchInProgramEditions(ref SearchModel model, List<string> tagIDList_lowerCase)
        {
            var programEditionResults = unitOfWork.ProgramEditionRepository.Get(filter: obj => tagIDList_lowerCase.All(word => obj.TagString.ToLower().Contains(word))
                && obj.Published == true, includeProperties: "Program").Take(100);

            for (int i = 0; i < programEditionResults.Count(); i++)
            {
                var programEdition = programEditionResults.ElementAt(i);
                SearchResult item = new SearchResult();
                item.Description = programEdition.ShortDescription;
                item.ImagePath = programEdition.Program.SmallLogoPath;
                item.PublishTime = programEdition.AirDate;
                item.ResultType = SearchResult.SearchResultType.ProgramEdition;

                item.RecordName = programEdition.EditionTittle;
                item.RecordID = programEdition.ID;

                // parent info
                item.ParentName = programEdition.Program.Name;
                item.ParentID = programEdition.Program.ID;

                // add to result
                model.SearchResultList.Add(item);
                model.NumberOfResults = model.SearchResultList.Count();
            }
        }


        private void searchInBlogRecords(ref SearchModel model, List<string> tagIDList_lowerCase)
        {
            var blogRecordResults = unitOfWork.BlogRecordRepository.Get(filter: obj => tagIDList_lowerCase.All(word => obj.TagString.ToLower().Contains(word))
                    && obj.Published == true, includeProperties: "Blog").Take(100);

            for (int i = 0; i < blogRecordResults.Count(); i++)
            {
                var blogRecord = blogRecordResults.ElementAt(i);
                SearchResult item = new SearchResult();
                item.Description = blogRecord.NoteFragment;
                item.ImagePath = blogRecord.Blog.SmallLogoPath;
                item.PublishTime = blogRecord.CreationDate;
                item.ResultType = SearchResult.SearchResultType.Blog;

                item.RecordName = blogRecord.Title;
                item.RecordID = blogRecord.ID;

                // parent info
                item.ParentName = blogRecord.Blog.Name;
                item.ParentID = blogRecord.Blog.ID;

                // add to result
                model.SearchResultList.Add(item);
                model.NumberOfResults = model.SearchResultList.Count();
            }
        }
    }
}

PascalWeb/Views/ProgramEdition/Details.cshtml
@model PascalWeb.DB.PageModels.ProgramEditionPageView


@{
 //   ViewBag.SocialInfo = Model.ProgramEdition.ShortDescription;
    ViewBag.SocialImage = Model.ProgramEdition.Program.MediumLogoPath;
}
@Html.Partial("_PageTittle", GeneralMethods.concatenateStrings("PascalFM", " - ",Model.ProgramEdition.EditionTittle))
        

@Html.Partial("_HeadNavigation", 1)

@Styles.Render("~/Content/RoxieTheme/css/style-custom-blog.css") 
@Styles.Render("~/Content/RoxieTheme/css/style-custom-articles.css") 
@Styles.Render("~/Content/RoxieTheme/css/style-custom-comment.css") 


    <!-- CONTENT -->
    <div class="l-content">
        <div class="container b-blogs">
            @{
                string formatDate = GeneralMethods.getFormatedDateAndTime(Model.ProgramEdition.AirDate);
            }
            <div class="">
                <section class="b-news b-news_blog" >
                    <article class="">  @*class="b-news__item"*@
                        <div class="b-news__item__head">
                            <span class="b-news__item__head__date">@formatDate</span>
                            <span class="b-news__item__head__comment">@Model.ProgramEdition.CommentsCounter.ToString()</span>
                            <span class="b-news__item__head__count-watch">@Model.ProgramEdition.ViewedCounter.ToString()</span>
                            @Html.ActionLink(Model.ProgramEdition.Program.Name, "Details", "Program", routeValues: new { id = Model.ProgramEdition.Program.ID },
                                htmlAttributes: new { @class = "b-news__item__head__title pull-right", withpjax = "withpjax" })
                        </div>
                        <div class="b-news__item__wrap">
                            <div class="display: inline-block;" style="vertical-align:middle" >

                                <div id="start_@Model.ProgramEdition.ID" style="display:inline-block; margin-left:27px;vertical-align:middle">     
                                    @*<a  onclick="changePLayStateForTile('start', @Model.ProgramEdition.ID, 'inline-block')" style = "display:inline-block;background: url('../../Content/Images/play.png') no-repeat center right;display:inline-block; height:48px; width:48px;vertical-align:middle;cursor: pointer;"> </a>*@
                                    <a  onclick="changeButtonAndPlay('start', @Model.ProgramEdition.ID, 'inline-block', '@Model.ProgramEdition.Content.AbsoluteFileUri', '@Model.ProgramEdition.Program.Name', 
                                        '@Model.ProgramEdition.EditionTittle')" style = "display:inline-block;background: url('../../Content/Images/play.png') no-repeat center right;display:inline-block; height:48px; width:48px;vertical-align:middle;cursor: pointer;"> </a>
                                
                                </div>

                                <div id="stop_@Model.ProgramEdition.ID" style="display:none; margin-left:27px; vertical-align:middle">
                                    @*<a  onclick="changePLayStateForTile('stop', @Model.ProgramEdition.ID, 'inline-block')"  style = "display:inline-block;background: url('../../Content/Images/pause.png') no-repeat center right;display:inline-block; height:48px; width:48px;vertical-align:middle;cursor: pointer;"> </a>*@
                                    <a  onclick="changeButtonAndPlay('stop', @Model.ProgramEdition.ID, 'inline-block', '@Model.ProgramEdition.Content.AbsoluteFileUri', '@Model.ProgramEdition.Program.Name', 
                                        '@Model.ProgramEdition.EditionTittle')"  style = "display:inline-block;background: url('../../Content/Images/pause.png') no-repeat center right;display:inline-block; height:48px; width:48px;vertical-align:middle;cursor: pointer;"> </a>                                
                                </div>


                                @Html.ActionLink( " " , "Download" , "AudioPlayer", new { programEditionID = Model.ProgramEdition.ID },
                                    new { style = "background: url('../../Content/Images/download.png') no-repeat center right;display:inline-block; margin-left:12px;height:48px; width:48px;vertical-align:middle"})

     
                                <span class="b-news__item__title-cat" style="vertical-align: middle;">@Model.ProgramEdition.EditionTittle</span>
                            </div>
                            <br />
                            <span class="b-news__item__desrc b-news__item__desrc_multicol">
                                @Model.ProgramEdition.ShortDescription
                            </span>
                        </div>
                        <div class="b-news__item__foot b-news__item__foot_mtb">
                            <div class="b-news__item__foot__social pull-right">
                                <script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script>
                                <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="small" data-yashareQuickServices="vkontakte,facebook" data-yashareTheme="counter"></div>

@*                                <a onclick="Share.vkontakte('PascalFM.ru','Pascal FM Программа','www.google.it/images/nav_logo195.png','Подробно')"> {шарь меня полностью}</a>*@

                            </div>
                            <div class="b-hashtags">
                                @{
                                    var tagList = PascalWeb.Controllers.TagController.stringToTagList(Model.ProgramEdition.TagString);
                                    
                                    for (int i = 0; i < tagList.Count; i++)
                                    {
                                        <span>@Html.ActionLink(tagList[i], "Search", "Search", routeValues: new { query = "#" + tagList[i] },
                                            htmlAttributes: new { @class = "b-news__item__foot__item", withpjax = "withpjax" })</span>
                                    }
                                }
                            </div>

                        </div>

                        <div class="b-news__item__foot b-news__item__foot_mtb">
                            @if (Model.ProgramEdition.ProgramEditionText != null && !string.IsNullOrEmpty(Model.ProgramEdition.ProgramEditionText.Note))
                            {
                                <span class="b-news__item__desrc">
                                    @Html.Raw(Model.ProgramEdition.ProgramEditionText.Note)
                                </span>
                            }
                        </div>
                    </article>
                </section>


                @if (Model.Recommendation != null && Model.Recommendation.LastProgramEditions.Count > 0)
                {
                    <div class="">
                        <h1 class="b-title-h1 b-title-h1-center b-title-h1_fs22">Рекомендуем также</h1>
                        @{Html.RenderPartial("..//ProgramEdition//_TileListView", Model.Recommendation.LastProgramEditions);}

                    </div>
                }

            <div id="_userCommentBox">
                @Html.Partial("_ViewCommentBox", Model.Comments)
            </div>
            </div>
        </div>
    </div>



<script type="text/javascript">
     @{
         ViewBag.firstEditionToSet = Model.ProgramEdition.ID;
     }
    $(document).ready(function () {
        audio = $('audio');
        editionID = @ViewBag.firstEditionToSet;
        
        // load next edition if nothing plays and something exists
        if (audio[0].currentTime == "0" && editionID != 0) {
            try {
                // загрузить первый выпуск - обращение к серверу
                $.ajax({
                    url: '/Home/AudioElement',
                    data: { programEditionID: editionID},
                    success: function (result) {
                        $('#mainAudio').html(result);
                    }
                });
            } catch (err) {
                alert('error');
            }
        }
    })
</script>

PascalWeb/Views/ProgramEdition/_TileList.cshtml
@model List<PascalWeb.DB.PageModels.LastProgramEditionPageModel.LastProgramEdition>


    @{
        for (int j = 0; j < Model.Count; j++)
        {
            var item = Model[j];
            ViewData["TILE_INDEX"] = j;
            @Html.Partial("..//ProgramEdition//_ViewTileProgramEdition", item, ViewData);
        }
    }

PascalWeb/Views/ProgramEdition/_TileListView.cshtml
@model List<PascalWeb.DB.PageModels.LastProgramEditionPageModel.LastProgramEdition>



    <div class="b-podcasts g-clearfix">
        @{
            @Html.Partial("..//ProgramEdition//_TileList", Model);
        }
    </div>


@*<script src="@Url.Content("~/Scripts/audio/generalAudioFunctions.js")" type="text/javascript")></script>*@
@*<script src="@Url.Content("~/Scripts/require.js")" type="text/javascript")></script>*@

<!-- TODO + когда переключаются страницы - остался случай со списком в - это в программах -->
<!-- также нажатие паузы на плеере!! -->
<script type="text/javascript">

    $(document).ready(function () {
        // нужно состояние смотреть - если пауза - то ничего не делать
        try {
            //var Mod = require('~/Scripts/audio/generalAudioFunctions');
            audio = getAudioControl();
            if (!audio[0].paused)
            {
                editionID = document.getElementById("currentTrackID").innerHTML;
                showAndHideControl('start', 'stop', editionID);
            }           
        } catch (exc) { }

    });
</script>

PascalWeb/Views/ProgramEdition/_TileListWithMoreButton.cshtml
@model PascalWeb.DB.AuxiliaryModels.ExpandingContainerModel<List<PascalWeb.DB.PageModels.LastProgramEditionPageModel.LastProgramEdition>>

    @{
        Guid guid;
        guid = Guid.NewGuid();
        string key = guid.ToString();
        key = key.Replace("-", "");
    }
    <div class="b-podcasts g-clearfix" id="_moreProgramEditions_@key">
        @{
            @Html.Partial("..//ProgramEdition//_TileListView", Model.Data);
        }
    </div>
    <button class="b-blck b-blck_bg-green" style="margin: 10px auto;" onclick="loadMoreEditions_@(key)()">Больше</button>



<script type="text/javascript">
    var page_@(key) = 0;
    var _inCallback_@(key) = false;

    loadMoreEditions_@(key) = function () {
 
        if (page_@(key) > -1 && !_inCallback_@(key)) {
            _inCallback_@(key) = true;
            page_@(key)++;
            $('#loadLayout').show();

            $.post("@Url.Action(Model.ActionName, 
                Model.ControllerName)", { "pageNumber": page_@(key) }, function (data) {
                if (data != '') {
                    $("#_moreProgramEditions_@key").append(data);
                }
                else {
                    page_@(key) = -1;
                }

                _inCallback_@(key) = false;
                $('#loadLayout').hide();
            });
        }
    }
</script>

PascalWeb/Views/ProgramEdition/_ViewCommentBox.cshtml
@model PascalWeb.DB.PageModels.CommentBoxModel

<div class="b-comments">
    <div class="b-comments__title">комментарии (@Model.CommentsList.Count.ToString())</div>
    <div class="g-clearfix">
        @if (@Model.UserLogo != null)
        {
            <img class="b-user-ava b-user-ava_40" src="@Model.UserLogo" />
        }
        @using (Ajax.BeginForm("AddComment", Model.ActionUpdateMethodInfo.Value, new AjaxOptions
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "_userCommentBox",
            LoadingElementId = "loadLayout",
            OnComplete = "clearField"
        }, new {@class="b-comments__form b-comments__form_top"}))
        {
            if (Request.IsAuthenticated)
            {
                @Html.TextArea("commentText", htmlAttributes: new { name = "commentText",  @class = "b-form__textarea b-comments__form__txtarea", placeholder= "Присоединиться к обсуждению (не более 500 символов)", @style="autocomplete:off"})
                <div class="b-comments__form__btn-wrap_al-r">
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </div>
            }
            else
            {
                <span style="font-size:small">Необходимо @Html.ActionLink("авторизоваться", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", withpjax = "withpjax" }) или зарегистрироваться, чтобы оставить комментарий</span>
                <hr />
            }
        }

        <div id="_userComments">
            @Html.Partial("..//ProgramEdition//_ViewCommentList", Model.CommentsList)
        </div>
    </div>                 
</div>



<script type="text/javascript">
    var page = 0;
    var _inCallback = false;

    function loadComments() {
        if (page > -1 && !_inCallback) {
            _inCallback = true;
            page++;
            $('div#loading').html('<p><img src="/Content/images/process.gif"></p>');
            
            $.post("@Url.Action(@Model.ActionUpdateMethodInfo.Key, 
                Model.ActionUpdateMethodInfo.Value)", { "pageNumber": page }, function (data) {
                if (data != '') {
                    $("#_moreProgramEditions").append(data);
                }
                else {
                    page = -1;
                }

                _inCallback = false;
                $('div#loading').empty();
            });
        }
    }

    var dcList = true;

    //alert('1. Обработчик window.scroll был добавлен. ');
    $(window).scroll(function () {

        if ($(window).scrollTop() > $(document).height() - $(window).height() - 10) {
            loadComments();
            //alert('конец');
        }
    });

    // for clearing textarea
    function clearField() {
        document.getElementById("commentText").value = "";
    }


</script>