PascalWeb/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using PascalWeb.Additional;
using PascalWeb.Additional.Audio;
using PascalWeb.Additional.Auth;
using PascalWeb.DB;
using PascalWeb.DB.AuxiliaryModels;
using PascalWeb.DB.Enumerators;
using PascalWeb.DB.PageModels;
using PascalWeb.DB.Repositories;
using PascalWeb.Additional.ImageProcessing;
using System.Drawing;
using PascalWeb.Additional.Storage;
using System.Data.Entity.Infrastructure;
using PascalWeb.Additional.Cache;

namespace PascalWeb.Controllers
{
    [DynamicAuthorizeAttribute]
    public class ProgramController : ControllerBase
    {
        UnitOfWork unitOfWork = new UnitOfWork();
       
        //
        // GET: /Program/

        //public ViewResultBase Index(int paginationNumber = 0)
        //{
        //    var lastProgramEditionPageModel = CasheManager.getData<LastProgramEditionPageModel>(eCasheEnumeration.FP_LAST_PROGRAM_EDITIONS, unitOfWork);
                
        //    // prepare data for audio player
        //    List<AudioTransferData> audioData = AudioManager.setPlayList(lastProgramEditionPageModel.LastProgramEditions);
        //    Session[AudioManager.PLAYLIST_SESSION_KEY] = audioData;

        //    // prepare model
        //    PaginationModel paginationmodel = new PaginationModel(1, paginationNumber, new ManageViewCommonModel("Program", "Index"));

        //    var model = new PageWithPagination<LastProgramEditionPageModel>(lastProgramEditionPageModel, paginationmodel);
        //    return PartialOrFullView("Index", model);
        //}



        public ViewResultBase Index(int? programID = null)
        {
            // get theme's list
            var programThemeList = HomeController.getThemes(unitOfWork, true, false);
            var themeWithProgramsList = new List<ListElementWithChildren<Program>>();

            for (int i = 0; i < programThemeList.Count(); i++)
            {
                var themeWithPrograms = new ListElementWithChildren<Program>(programThemeList.ElementAt(i).Name, programThemeList.ElementAt(i).Program);
                themeWithProgramsList.Add(themeWithPrograms);
            }

            List<UserInfoModel> authorList = HomeController.getAuthorList(unitOfWork, true, false);

            ProgramThemePageModel model = null;
            // if particlural program was chosen
            if (programID.HasValue)
            {
                ProgramPageModel programInfo = ((ViewResultBase)Details(programID.Value, 0)).Model as ProgramPageModel;
                model = new ProgramThemePageModel(themeWithProgramsList, authorList, programInfo);
            }
            else
            {
                // else show popular programs
                var popularProgramList = getPopularProgramList();
                model = new ProgramThemePageModel(themeWithProgramsList, authorList, popularProgramList);
            }

            return PartialOrFullView(model: model);
        }

        
        IEnumerable<Program> getPopularProgramList()
        {
            var popularProgram = unitOfWork.ProgramRepository.Get(orderBy: q => q.OrderByDescending(x => x.ProgramEdition.Sum(s => s.ViewedCounter)));
            return popularProgram;
        }

        //public ViewResultBase ShowProgramsByTheme(int? programID = null)
        //{
        //    System.Diagnostics.Debug.WriteLine("time00 home: " + DateTime.Now.ToString("hh.mm.ss.ffffff"));

        //    // get theme's list
        //    var programThemeList = unitOfWork.ProgramThemeRepository.Get(orderBy: q => q.OrderBy(x => x.Name), includeProperties:"Program");
        //    var themeWithProgramsList = new List<ThemeWithChildren<Program>>();

        //    for (int i = 0; i < programThemeList.Count(); i++)
        //    {
        //        var themeWithPrograms = new ThemeWithChildren<Program>(programThemeList.ElementAt(i).Name, programThemeList.ElementAt(i).Program);
        //        themeWithProgramsList.Add(themeWithPrograms);
        //    }
        //    System.Diagnostics.Debug.WriteLine("time01 home: " + DateTime.Now.ToString("hh.mm.ss.ffffff"));

        //    ProgramThemePageModel model = null;
        //    // if particlural program was chosen
        //    if (programID.HasValue)
        //    {
        //        ProgramPageModel programInfo = ((ViewResultBase)Details(programID.Value, 0)).Model as ProgramPageModel;
        //        model = new ProgramThemePageModel(themeWithProgramsList, null, programInfo);
        //    }
        //    else
        //    {
        //        System.Diagnostics.Debug.WriteLine("time1 home: " + DateTime.Now.ToString("hh.mm.ss.ffffff"));
        //        // else show popular programs
        //        var popularProgramList = getPopularProgramList();
        //        model = new ProgramThemePageModel(themeWithProgramsList, null, popularProgramList);
        //        System.Diagnostics.Debug.WriteLine("time2 home: " + DateTime.Now.ToString("hh.mm.ss.ffffff"));
        //    }

        //    return PartialOrFullView(model:model);
        //}

       // public ViewResultBase ShowProgramsByAuthors(long? userID = null)
       // {
       //     System.Diagnostics.Debug.WriteLine("time00 home: " + DateTime.Now.ToString("hh.mm.ss.ffffff"));
       //     // prepare left author's list

       //     var authorQuery = CasheManager.getData<List<UserAuth>>(eCasheEnumeration.FP_PROGRAM_TOP_AUTHOR_LIST, unitOfWork);
       ////     var authorQuery = unitOfWork.ProgramAuthorsRepository.Get(includeProperties: "UserAuth, Program").Select(obj => obj.UserAuth).Distinct();
       //     List<UserInfoModel> authorList = new List<UserInfoModel>();
       //     for (int i = 0; i < authorQuery.Count(); i++)
       //     {
       //         UserAuth _user = authorQuery[i];
       //         UserInfoModel userModel = new UserInfoModel(_user.ID, _user.Email, _user.Name, _user.Surname, _user.SmallLogoPath);
       //         authorList.Add(userModel);
       //     }
       //     System.Diagnostics.Debug.WriteLine("time01 home: " + DateTime.Now.ToString("hh.mm.ss.ffffff"));
         
       //     ProgramAuthorPageModel model = new ProgramAuthorPageModel(authorList);

       //     if (userID.HasValue) // get specific information about author
       //     {
       //         ProgramAuthorPageModel.AuthorInfoModel authorInfo = new ProgramAuthorPageModel.AuthorInfoModel();
       //         authorInfo.UserData = new UserUnitedModel();
       //         authorInfo.UserData.UserAuth = unitOfWork.UserAuthRepository.GetOneItem(obj => obj.ID == userID, "ProgramAuthors, ProgramAuthors.Program");
       //         authorInfo.UserData.UserInfo = unitOfWork.UserInfoRepository.GetByID(userID);

       //         var currentUserID = getCurrentUserID();
       //         var authorProgramList = new List<KeyValuePair<Program, bool?>>();
       //         for (int i = 0; i < authorInfo.UserData.UserAuth.ProgramAuthors.Count; i++)
       //         {
       //             var pa = authorInfo.UserData.UserAuth.ProgramAuthors.ElementAt(i);
       //             // check whether user is subscribed to program
       //             bool? isSubscribedToProgram = currentUserID.HasValue ? SubscriptionController.checkProgramSuscription(unitOfWork, currentUserID, pa.ProgramID) : null;
       //             authorProgramList.Add(new KeyValuePair<Program, bool?>(pa.Program, isSubscribedToProgram));
       //         }
       //         authorInfo.UserData.UserPrograms = authorProgramList;

       //         // check blog subscription
       //         var blogID = unitOfWork.BlogRepository.Get(filter: obj => obj.AuthorID == userID.Value).Select(obj => obj.ID).FirstOrDefault();
       //         bool? isSubscribedToBlog = currentUserID.HasValue ? SubscriptionController.checkBlogSuscription(unitOfWork, currentUserID, blogID) : null;
       //         authorInfo.BlogSubscription = new KeyValuePair<int?, bool?>(blogID, isSubscribedToBlog);


       //         // get last editions
       //         //var authorProgramIDList = unitOfWork.ProgramAuthorsRepository.Get(filter: obj => obj.UserID == userID).Select(obj => obj.ProgramID);
       //         var authorProgramIDList = authorInfo.UserData.UserAuth.ProgramAuthors.Select(obj => obj.ProgramID);

       //         // get last program editions
       //         var lastEditions =  unitOfWork.ProgramEditionRepository.Get(filter: obj => obj.Published == true && authorProgramIDList.Contains(obj.ProgramID), 
       //             orderBy: q => q.OrderByDescending(x => x.AirDate), includeProperties: "Content, Program");
       //         LastProgramEditionPageModel lastProgramEditionPageModel = LastProgramEditionPageModel.getLastProgramEditionModel(lastEditions);
       //         authorInfo.lastEditions = lastProgramEditionPageModel.LastProgramEditions;

       //         // prepare data for audio player
       //         List<AudioTransferData> audioData = AudioManager.setPlayList(lastProgramEditionPageModel.LastProgramEditions);
       //         Session[AudioManager.PLAYLIST_SESSION_KEY] = audioData;

       //         // get last blog records
       //         var blogRecords = unitOfWork.BlogRecordRepository.Get(filter: obj => obj.Published == true && obj.Blog.AuthorID == userID.Value, orderBy: q => q.OrderByDescending(x => x.CreationDate)).ToList();
       //         authorInfo.lastBlogRecords = blogRecords;

       //         model.AuthorInfo = authorInfo;
       //     }
       //     else // get list of best authors
       //     {
       //         model.PopularAuthors = authorQuery;
       //     }

       //     return PartialOrFullView(model: model);
       // }


        //
        // GET: /Program/Details/5

        public ActionResult Details(int id = 0, int paginationNumber = 0) 
        {

PascalWeb/Views/Shared/_Footer.cshtml
<footer class="l-foot" style="margin-top: 0px;">
    <div class="container ">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin:0px">
        <div class="b-copyright col-xs-4 col-sm-4 col-md-4 col-lg-4" style="margin:0px">
            <p class="b-copyright__text">&copy; Pascal FM 2014-2016.</p>
            <p class="b-copyright__text">Все права защищены.</p>
        </div>
        <div class="b-foot-nav col-xs-4 col-sm-4 col-md-4 col-lg-4" style="margin:0px">
            @Html.ActionLink("Контакты", "Contact", "Home", null, new { withpjax = "withpjax", @class = "b-foot-nav__link" })
            @Html.ActionLink("О проекте", "About", "Home", null, new { withpjax = "withpjax", @class = "b-foot-nav__link", @style = "white-space:nowrap" })
        </div>
@*        <div class="b-social b-custom-style" >
            <script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script>
            <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="facebook,vkontakte,twitter,gplus"></div>
                <div class="b-share">
                    <a class="b-share__icon b-share__icon_act b-share__icon_facebook" href="http://facebook.com" target="_blank" title="">facebook</a>
                    <a class="b-share__icon b-share__icon_act b-share__icon_vkontakte" href="https://vk.com/pascalfm" target="_blank" title="" >vkontakte</a>
                    <a class="b-share__icon b-share__icon_act b-share__icon_twitter" href="http://twitter.com" target="_blank" title="">twitter</a>
                    <a class="b-share__icon b-share__icon_act b-share__icon_gplus" href="http://plus.google.com" target="_blank" title="">gplus</a>
                </div>
        </div>*@
            <div class="b-contact__share b-custom-style col-xs-4 col-sm-4 col-md-4 col-lg-4" style="margin:0px;padding: 15px 0 15px;">
                <div class="" style="text-align:center">

                        <a class="b-share__icon b-share__icon_act b-share__icon_facebook"  href="https://www.facebook.com/Pascal-FM-451186858406101/" target="_blank" title="" style="margin: 0 9px;">facebook</a>
                        <a class="b-share__icon b-share__icon_act b-share__icon_vkontakte" href="https://vk.com/pascalfm" target="_blank" title="" style="margin: 0 9px;">vkontakte</a>

                        @*<a class="
                         b-share__icon_act b-share__icon_twitter" href="https://twitter.com/Pascal__FM" target="_blank" title="" style="margin: 0 9px;">twitter</a>*@
                        @*<a class="b-share__icon b-share__icon_act b-share__icon_gplus" href="https://plus.google.com/u/0/communities/109733084503503733330" target="_blank" title="" style="margin: 0 9px;">gplus</a>*@

                </div>
            </div>
        </div>
    </div>
</footer>

PascalWeb/Views/Shared/_HeadNavigation.cshtml
@model int

@Html.Partial("..//Shared//Counters/YandexMetric")

<nav class="b-nav navbar yamm navbar-default navbar-fixed-top" style="margin-top:65px;border-style: solid;border-bottom: 1px solid  #16A085;" >
    <div class="container">

        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div >
                @Html.ActionLink("pascal", "Index", "Home", null, new { @class="site-logo", @style="position:relative;float:left;margin-left:10px;margin-top:20px;margin-bottom:15px",withpjax = "withpjax"})
            </div>
        </div>

        <div id="navbarCollapse" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right b-nav__list">
                    @if(@Model == 1) { 
                        @:<li class="dropdown b-nav__list__item active">
                    }
                    else{ @:<li class="dropdown b-nav__list__item">  
                    }
                    @Html.ActionLink("Подкасты", "Index", "Program", null, new {@class="b-nav__list__item__link", withpjax = "withpjax" })
                    @*<a href="#" class="dropdown-toggle b-nav__list__item__link" data-toggle="dropdown">Подкасты <b class="caret"></b></a>*@
@*                    <ul class="dropdown-menu maincolor" style="color:black;font-size:16px">
                        <li>
                            <a href="">@Html.ActionLink("Последние выпуски", "Index", "Program", null, new { withpjax = "withpjax"})</a>
                        </li>
                        <li>
                            <a href="">@Html.ActionLink("Выпуски по темам", "ShowProgramsByTheme", "Program", null, new { withpjax = "withpjax"})</a>
                        </li>
                        <li>
                            <a href="">@Html.ActionLink("Выпуски по авторам", "ShowProgramsByAuthors", "Program", null, new { withpjax = "withpjax"})</a>
                        </li>
                    </ul>*@
                </li>

                @if(@Model == 2) { 
                    @:<li class="b-nav__list__item active">
                }
                else{ @:<li class="b-nav__list__item">  
                }
                    @Html.ActionLink("Блоги", "Index", "BlogRecord", null, new {@class="b-nav__list__item__link", withpjax = "withpjax" })
                </li>
                @if(@Model == 3) { 
                    @:<li class="b-nav__list__item active">
                }
@*                else{ @:<li class="b-nav__list__item">  
                }
                    @Html.ActionLink("Новости", "News", "BlogRecord", null, new {@class="b-nav__list__item__link", withpjax = "withpjax" })
                </li>*@

                @Html.Partial("_LoginPartial", @Model == 4)
       
                <li class="b-nav__list__item">
                    @using (Ajax.BeginForm(actionName: "Search", controllerName: "Search", routeValues: null, ajaxOptions: new AjaxOptions
                    {
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "ajax_main_container",
                        LoadingElementId = "loadLayout"
                    }, htmlAttributes: new { @class = "b-form-search", @style = "padding-bottom:10px" }))
                    {          
                        <div class="b-form-search__field">
                            <input type="text" id= "query" name="query" placeholder="Поиск" style="vertical-align:central" class="b-form-search__field__inp">
                            <button type="submit" class="b-form-search__field__btn" style="margin-left:10px;"></button>
                        </div>
                    }
                </li>
            </ul>
        </div>
    </div>
</nav>

@*<script type="text/javascript">
    //Hamburger menu toggle
    $(".navbar-nav li a").click(function (event) {
        // check if window is small enough so dropdown is created
        var toggle = $(".navbar-toggle").is(":visible");
        if (toggle) {
            $(".navbar-collapse").collapse('hide');
        }
    });
</script>*@

PascalWeb/Views/Shared/_PageTittle.cshtml
@model string

@{
    ViewBag.Title = Model;
}

<title>@Model</title>

PascalWeb/Views/Shared/_PjaxLayout.cshtml
<title>@ViewBag.Title</title>
@RenderBody()

PascalWeb/Views/Shared/_pagination.cshtml
@model PascalWeb.DB.AuxiliaryModels.PaginationModel

<div class="b-pager">
    
   @{
       if(Model != null)
       {
            int pageCount = Model.PageCount;
            int pageNumber = Model.CurrentPageNumber;

            if (pageCount > 1)
            {
                int standartDistance = 3;
                for (int i = 0; i < pageCount; i++)
                {
                    RouteValueDictionary rvDic = new RouteValueDictionary(); //new { paginationNumber = i, blogID = "2"}
                    rvDic.Add("paginationNumber", i.ToString());
                    
                    if (Model.ManageViewCommonModel.RouteValueDictionary != null)
                    {
                        for (int k = 0; k < Model.ManageViewCommonModel.RouteValueDictionary.Count; k++)
                        {
                            var element = Model.ManageViewCommonModel.RouteValueDictionary.ElementAt(k);
                            rvDic.Add(element.Key, element.Value);
                        }
                    }

                    // new { @class="b-pager__link b-pager__link_unactive", withpjax = "withpjax" }
                    Dictionary<string, object> htmlAttributesActive = new Dictionary<string, object>() { 
                        {"class", "b-pager__link b-pager__link_active"},
                        {"withpjax", "withpjax"} };
                    Dictionary<string, object> htmlAttributesInactive = new Dictionary<string, object>() { 
                        {"class", "b-pager__link b-pager__link_unactive"},
                        {"withpjax", "withpjax"} };
                    
                    int distance = Math.Abs(i - pageNumber);
                    
                    if (distance == 0)
                    {
                        <a class="b-pager__link b-pager__link_active">@Html.ActionLink((i + 1).ToString(), Model.ManageViewCommonModel.ActionName, Model.ManageViewCommonModel.ControllerName, routeValues: rvDic, htmlAttributes: htmlAttributesActive)</a>
                        continue;
                    }
                    
                    if (distance < standartDistance)
                    {
                        <a class="b-pager__link b-pager__link_unactive">@Html.ActionLink((i + 1).ToString(), Model.ManageViewCommonModel.ActionName, Model.ManageViewCommonModel.ControllerName, routeValues: rvDic, htmlAttributes: htmlAttributesInactive)</a>
                        continue;
                    }
                    
                    if(i == 0 || i == (pageCount - 1))
                    {
                        <a class="b-pager__link b-pager__link_unactive">@Html.ActionLink((i + 1).ToString(), Model.ManageViewCommonModel.ActionName, Model.ManageViewCommonModel.ControllerName, routeValues: rvDic, htmlAttributes: htmlAttributesInactive)</a>
                        continue;
                    }
                    
                    if (distance < standartDistance + 1)
                    {
                        <a class="b-pager__link b-pager__link_unactive">...</a>
                        continue;
                    }
                        
                   /* if (pageNumber == i) {
                        <a class="b-pager__link b-pager__link_active">@Html.ActionLink((i + 1).ToString(), Model.ManageViewCommonModel.ActionName, Model.ManageViewCommonModel.ControllerName, new { paginationNumber = i}, new { @class="b-pager__link b-pager__link_active", withpjax = "withpjax" })</a>
                    } else {
                        <a class="b-pager__link b-pager__link_unactive">@Html.ActionLink((i + 1).ToString(), Model.ManageViewCommonModel.ActionName, Model.ManageViewCommonModel.ControllerName, new { paginationNumber = i}, new { @class="b-pager__link b-pager__link_unactive", withpjax = "withpjax" })</a>
                    }*/

                }
            }
        }
   }

@*  <li><a href="#">&laquo;</a></li>
  <li><a href="#">1</a></li>
  <li><a href="#">5</a></li>
  <li><a href="#">&raquo;</a></li>
    <li class="active">@Html.ActionLink("Последние выпуски", "Index", "Program", null, new { withpjax = "withpjax" })</li>*@
</div>