PascalWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PascalWeb.DB;
using PascalWeb.DB.Enumerators;
using PascalWeb.DB.Repositories;
using PascalWeb.DB.PageModels;
using PascalWeb.DB.AuxiliaryModels;
using PascalWeb.Additional;
using PascalWeb.DB.PageModels.Specific;

namespace PascalWeb.Controllers
{
    //[DynamicAuthorizeAttribute]
    public class AdminController : ControllerBase
    {
        UnitOfWork unitOfWork = new UnitOfWork();

        /// <summary>
        /// get programs
        /// </summary>
        /// <returns></returns>
        public ActionResult AdminProgramView()
        {
            var currentUserID = getCurrentUserID(); //Membership.GetUser().ProviderUserKey
            string role = unitOfWork.UserManagment.getUserRoleNameByUserID(currentUserID.Value);

            var programList = new List<Program>();
            if (GeneralMethods.compareStrings(role, eUserRoles.superadmin.ToString()) || GeneralMethods.compareStrings(role, eUserRoles.admin.ToString()))
            {
                programList = unitOfWork.ProgramRepository.Get(orderBy: q => q.OrderBy(x => x.Name), includeProperties: "ProgramAndTag, ProgramAndTag.Tag").ToList();
            }
            else
            {
                programList = unitOfWork.ProgramAuthorsRepository.Get(filter: obj => obj.UserID == currentUserID,
                    orderBy: q => q.OrderBy(x => x.Program.Name), includeProperties: "Program.ProgramAndTag, Program.ProgramAndTag.Tag").Select(s => s.Program).ToList();
            }

            return PartialOrFullView(model: programList);
        }

        /// <summary>
        /// get program editions
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AdminProgramEditionView(int programID)
        {
            var currentUserID = getCurrentUserID().Value;
            string role = unitOfWork.UserManagment.getUserRoleNameByUserID(currentUserID);

            var programEditionList = new List<ProgramEdition>();
            if (GeneralMethods.compareStrings(role, eUserRoles.superadmin.ToString()) ||
                GeneralMethods.compareStrings(role, eUserRoles.admin.ToString()))
            {
                programEditionList = unitOfWork.ProgramEditionRepository.Get(filter: obj => obj.ProgramID == programID, orderBy: q => q.OrderByDescending(x => x.AirDate)).ToList();
            }
            else
            {
                // additional - check whether current user is author of program
                var checkAuthor = unitOfWork.ProgramAuthorsRepository.Count(filter: obj => obj.ProgramID == programID && obj.UserID == currentUserID);
                if (checkAuthor > 0)
                {
                    // it is necessary to relate user with program's author (not with program edition's author)
                    programEditionList = unitOfWork.ProgramEditionRepository.Get(filter: obj => obj.ProgramID == programID,
                        orderBy: q => q.OrderByDescending(x => x.AirDate)).ToList();
                }
                //programEditionList = unitOfWork.ProgramEditionAuthorsRepository.Get(filter: obj => obj.UserID == currentUserID && obj.ProgramEdition.Program.ID == programID,
                //    orderBy: q => q.OrderByDescending(x => x.ProgramEdition.AirDate)).Select(s => s.ProgramEdition).ToList();
            }

            ViewData.Add("programID", programID);
            return PartialOrFullView(model: programEditionList);
        }

        /// <summary>
        /// get users
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AdminUserView(string userData, int? roleID)
        {
            getUserRoleList();

            var userInfoList = new List<UserInfoModel>();
            var userAuths = new List<UserAuth>();
            if (!string.IsNullOrWhiteSpace(userData) || roleID.HasValue)
            {
                userAuths = unitOfWork.UserManagment.searchUsersByDataAndRole(userData, roleID, 100).ToList();
                userInfoList = UserInfoModel.convertFromToUserInfoList(userAuths);
            }
            else
            {
                userAuths = unitOfWork.UserManagment.searchAllUsersExceptRole(eUserRoles.generaluser, 100).ToList();
                userInfoList = UserInfoModel.convertFromToUserInfoList(userAuths);
            }

            UserSearchModel model = new UserSearchModel(userData, roleID);
            model.UserList = userInfoList;
            return PartialOrFullView(model: model);
        }

        ///// <summary>
        ///// search users
        ///// </summary>
        ///// <returns></returns>
        //[HttpGet]
        //public ActionResult UserSearch(string userData)
        //{
        //    var userInfoList = new List<UserInfoModel>();
        //    if (!string.IsNullOrWhiteSpace(userData))
        //    {
        //        var userAuths = new List<UserAuth>();
        //        userAuths = unitOfWork.UserManagment.searchUsersByNameAndEmail(userData, 100).ToList();
        //        userInfoList = UserInfoModel.convertFromToUserInfoList(userAuths);
        //    }
        //    else
        //    {
        //        var userAuths = new List<UserAuth>();
        //        userAuths = unitOfWork.UserManagment.searchUsersByRole(eUserRoles.journalist, 100).ToList();
        //        userInfoList = UserInfoModel.convertFromToUserInfoList(userAuths);
        //    }

        //    return PartialOrFullView("_userTable", userInfoList);
        //}

        [HttpGet]
        public ActionResult AdminUserRights()
        {
            var controllerList = SiteAnalysis.GetControllerNames().OrderBy(x => x).ToList();

            List<SiteActionModel> controllersWithAtions = new List<SiteActionModel>();

            for (int i = 0; i < controllerList.Count; i++)
            {
                var actionList = SiteAnalysis.ActionNames(controllerList[i]);
                var modifiedActionList = actionList.OrderBy(x => x).Distinct().ToList();

                var actionRuleList = new SortedList<string, ActionRule>();

                for (int j = 0; j < modifiedActionList.Count; j++)
                {
                    ActionRule actionRule = new ActionRule(modifiedActionList[j], new RightFeatures());
                    actionRuleList.Add(modifiedActionList[j], actionRule);
                }
                SiteActionModel item = new SiteActionModel(controllerList[i], actionRuleList);
                controllersWithAtions.Add(item);
            }

            actualizationRightModel(ref controllersWithAtions);

            return PartialOrFullView(model: controllersWithAtions);

        }

        /// <summary>
        /// get information about availibility of pages for each role
        /// </summary>
        /// <param name="model"></param>
        void actualizationRightModel(ref List<SiteActionModel> model)
        {
            for (int i = 0; i < model.Count; i++)
            {
                var itemFromModel = model[i];

                var query = unitOfWork.UserRightRepository.Get(filter: obj => obj.ControllerName.ToLower().CompareTo(itemFromModel.ControllerName) == 0,
                    includeProperties: "UserRole");

                for (int j = 0; j < query.Count(); j++)
                {
                    var right = query.ElementAt(j);
                    if (itemFromModel.ActionRules.ContainsKey(right.ActionName))
                    {
                        var actionRuleIndex = itemFromModel.ActionRules.Keys.IndexOf(right.ActionName);
                        string userRoleName = right.UserRole.Name;
                        if (GeneralMethods.compareStrings(userRoleName, eUserRoles.admin.ToString()) && right.IsAvailable)
                            itemFromModel.ActionRules.Values[actionRuleIndex].Rights.ForAdministrator = true;

                        if (GeneralMethods.compareStrings(userRoleName, eUserRoles.editor.ToString()) && right.IsAvailable)
                            itemFromModel.ActionRules.Values[actionRuleIndex].Rights.ForEditor = true;

                        if (GeneralMethods.compareStrings(userRoleName, eUserRoles.generaluser.ToString()) && right.IsAvailable)
                            itemFromModel.ActionRules.Values[actionRuleIndex].Rights.ForGeneralUser = true;

                        if (GeneralMethods.compareStrings(userRoleName, eUserRoles.journalist.ToString()) && right.IsAvailable)
                            itemFromModel.ActionRules.Values[actionRuleIndex].Rights.ForJournalist = true;

                        if (GeneralMethods.compareStrings(userRoleName, eUserRoles.moderator.ToString()) && right.IsAvailable)
                            itemFromModel.ActionRules.Values[actionRuleIndex].Rights.ForModerator = true;

                        //if (GeneralMethods.compareStrings(userRoleName, eUserRoles.superadmin.ToString()) && right.IsAvailable)
                        //    itemFromModel.ActionRules.Values[j].Rights. = true;

                        if (GeneralMethods.compareStrings(userRoleName, eUserRoles.withoutauth.ToString()) && right.IsAvailable)
                            itemFromModel.ActionRules.Values[actionRuleIndex].Rights.ForNotAuth = true;
                    }
                }
            }
        }


        [HttpGet]
        public ActionResult SetRight(string controllerName, string actionName, bool allRoles, eUserRoles userRole, bool isAddtion)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(actionName))
                {
                    if (!allRoles)
                    {
                        int? userRoleID = unitOfWork.UserManagment.getUserRoleIDByName(userRole.ToString());
                        var actionNameList = SiteAnalysis.ActionNames(controllerName + "controller").OrderBy(x => x).Distinct().ToList();

PascalWeb/Controllers/SearchController.cs
using PascalWeb.DB.PageModels;
using PascalWeb.DB.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PascalWeb.Controllers
{
    public class SearchController : ControllerBase
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        //
        // GET: /Search/
        [HttpGet]
        public ActionResult Index(SearchModel modelData)
        {
            searchIt(modelData);
            return PartialOrFullView(model: modelData);
        }

        [HttpGet]
        public ActionResult PartialSearch(SearchModel modelData)
        {
            searchIt(modelData);
            return base.PartialView("_resultItems", model: modelData);
        }

        [HttpGet]
        public ActionResult Search(string query, SearchResult.SearchResultType searchType = SearchResult.SearchResultType.All)
        {
            SearchModel model = new SearchModel();
            model.Query = query;
            model.IsHashTag = true;
            model.IsSearchInPrograms = true;
            model.SearchType = searchType;
            return Index(model);
        }

        private List<string> getTagNameList(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
                return new List<string>();
            var array = query.Split(new char[] { ' ' });
            var result = (from word in array
                         where string.IsNullOrWhiteSpace(word) == false
                         select word.Replace('#', ' ').Trim().ToLower()).ToList<string>();

            return result;
        }


        private void searchIt(SearchModel model)
        {
            model.SearchResultList = new List<SearchResult>();
            //if (model.IsHashTag)
            {
                List<string> tagIDList_lowerCase = getTagNameList(model.Query);
                if (string.IsNullOrEmpty(model.Query))
                    return;

                searchInProgramEditions(ref model, tagIDList_lowerCase);
                searchInBlogRecords(ref model, tagIDList_lowerCase);

                model.SearchResultList = model.SearchResultList.OrderByDescending(q => q.PublishTime).ToList();
            }
        }

        private void searchInProgramEditions(ref SearchModel model, List<string> tagIDList_lowerCase)
        {
            var programEditionResults = unitOfWork.ProgramEditionRepository.Get(filter: obj => tagIDList_lowerCase.All(word => obj.TagString.ToLower().Contains(word))
                && obj.Published == true, includeProperties: "Program").Take(100);

            for (int i = 0; i < programEditionResults.Count(); i++)
            {
                var programEdition = programEditionResults.ElementAt(i);
                SearchResult item = new SearchResult();
                item.Description = programEdition.ShortDescription;
                item.ImagePath = programEdition.Program.SmallLogoPath;
                item.PublishTime = programEdition.AirDate;
                item.ResultType = SearchResult.SearchResultType.ProgramEdition;

                item.RecordName = programEdition.EditionTittle;
                item.RecordID = programEdition.ID;

                // parent info
                item.ParentName = programEdition.Program.Name;
                item.ParentID = programEdition.Program.ID;

                // add to result
                model.SearchResultList.Add(item);
                model.NumberOfResults = model.SearchResultList.Count();
            }
        }


        private void searchInBlogRecords(ref SearchModel model, List<string> tagIDList_lowerCase)
        {
            var blogRecordResults = unitOfWork.BlogRecordRepository.Get(filter: obj => tagIDList_lowerCase.All(word => obj.TagString.ToLower().Contains(word))
                    && obj.Published == true, includeProperties: "Blog").Take(100);

            for (int i = 0; i < blogRecordResults.Count(); i++)
            {
                var blogRecord = blogRecordResults.ElementAt(i);
                SearchResult item = new SearchResult();
                item.Description = blogRecord.NoteFragment;
                item.ImagePath = blogRecord.Blog.SmallLogoPath;
                item.PublishTime = blogRecord.CreationDate;
                item.ResultType = SearchResult.SearchResultType.Blog;

                item.RecordName = blogRecord.Title;
                item.RecordID = blogRecord.ID;

                // parent info
                item.ParentName = blogRecord.Blog.Name;
                item.ParentID = blogRecord.Blog.ID;

                // add to result
                model.SearchResultList.Add(item);
                model.NumberOfResults = model.SearchResultList.Count();
            }
        }
    }
}

PascalWeb/Views/BlogRecord/Create.cshtml
@model PascalWeb.DB.BlogRecord

@Html.Partial("_PageTittle", "PascalFM - Запись блога")
@Html.Partial("_HeadNavigation", 4)


<div class="l-content">
    <div class="container">

        @if (Model == null || Model.ID <= 0)
        {
            <h1 class="b-title-h1 b-title-h1-center b-title-h1_fs22">Добавление записи</h1>
        }
        else
        {
            <h1 class="b-title-h1 b-title-h1-center b-title-h1_fs22">Редактирование записи</h1>
        }

        <div class = "col-xs-12 col-sm-12 col-md-12 col-lg-12 form-horizontal">
            @{
                List<PascalWeb.DB.Tag> tagList = null;
                if(Model != null) {
                    tagList = Model.BlogRecordAndTag.Select(obj => obj.Tag).ToList();
                }
                <div >
                    @{Html.RenderPartial("..//Tag//_tagSelectionView", tagList);}
                </div>
            }
        </div>

        @using (Html.BeginForm("CreateOrEdit", "BlogRecord", FormMethod.Post, new
        {
            enctype = "multipart/form-data",
            @class = "col-xs-12 col-sm-12 col-md-12 col-lg-12 form-horizontal",
            role = "form",
            @style = "margin:0px"
        }))
        {

            @Html.ValidationSummary(true, null, htmlAttributes: new { @style = "color:red" })

            <fieldset>      
                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.CreationDate)
                @Html.HiddenFor(model => model.BlogID)
                @Html.HiddenFor(model => model.UserID)
                @Html.HiddenFor(model => model.IsModerated)
                @Html.HiddenFor(model => model.ViewedCounter)
                @Html.HiddenFor(model => model.CommentsCounter)
                @Html.HiddenFor(model => model.Published)

                @Html.ValidationMessageFor(model => model.NoteFragment, null, htmlAttributes: new { @style = "color:red;"})

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control input-md", placeholder= "Название" })
                        @Html.ValidationMessageFor(model => model.Title, null, htmlAttributes: new { @style = "color:red;"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-lg-offset-2">
                        <p style ="margin:20px">Чтобы отделить краткое описание текста от всего текста записи, используйте выделенную красным кнопку 
                            <img src="~/Content/img/help/page_breaker.jpg" width="150"/>
                        </p>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-9 col-md-9">
                        @Html.TextAreaFor(model => model.Note, htmlAttributes: new { @style = "min-height:500px"})
                        @Html.ValidationMessageFor(model => model.Note, null, htmlAttributes: new { @style = "color:red;"})
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align:center;">
@*                    <button type="button" class="btn btn-default" style="width:100px"  onclick="backToPreviousPage();">Отмена</button>*@
                    @Html.ActionLink("Отмена", "AdminBlogView", "Admin", 
                            new { blogID = Model.BlogID}, htmlAttributes: new { @class = "btn btn-default", @style="width:100px", withpjax = "withpjax" })
                    <button name="action:Edit" type="submit" class="btn btn-success " style="width:100px;margin-left:10px">Сохранить</button>
                </div>
            </fieldset>
        }

@*        <script type="text/javascript">
            $(document).ready(function () {
                alert('1');
                $('#tinymce').init(
                    {
                        width: "1000"
                    });

                alert('2');
            })
        </script>*@

        <div>

            <h3>Загрузка изображений для записи</h3>
            @using (Html.BeginForm("UploadImage", "BlogRecord", FormMethod.Post, 
	            new { enctype = "multipart/form-data", id="ImgForm", 
		            name="ImgForm", target="UploadTarget",
                    @style="margin-top:20px"
                }))
            {
	            <input class="btn btn-info col-xs-3" style="height:40px;min-width:300px" type="file" name="imageFile" />
	            <input class="btn btn-info col-xs-3" style="height:40px;min-width:300px;margin-left:10px" type="button" value="Добавить изображение" onclick="UploadImage()" />
            }
            <br />
            <iframe id="UploadTarget" name="UploadTarget" onload="UploadImage_Complete();" style="position: absolute; left: -999em; top: -999em;"></iframe>
            <div id="Images" class="col-xs-12 col-sm-12 col-md-12 col-lg-12"></div>

        </div>
    </div>
</div>

<script type="text/javascript">
	var isFirstLoad = true;

	function UploadImage() {
		$("#ImgForm").submit();
	}

	function UploadImage_Complete() {
		//Check to see if this is the first load of the iFrame
		if (isFirstLoad == true) {
			isFirstLoad = false;
			return;
		}

		//Reset the image form so the file won't get uploaded again
		document.getElementById("ImgForm").reset();

		//Grab the content of the textarea we named jsonResult .  This shold be loaded into 
		//the hidden iFrame.
		var newImg = $.parseJSON($("#UploadTarget").contents().find("#jsonResult")[0].innerHTML);

		//If there was an error, display it to the user
		if (newImg.IsValid == false) {
			alert(newImg.Message);
			return;
		}

		//Create a new image and insert it into the Images div.  Just to be fancy, 
		//we're going to use a "FadeIn" effect from jQuery
		var imgDiv = document.getElementById("Images");
		var img = new Image();
		img.src = newImg.ImagePath;
	//	img.width = 200;

        // create textbox with uri
		var input = document.createElement('input');
		input.type = "text";
		input.value = newImg.ImagePath;
		input.readOnly = true;

	    // create label
		var label = document.createElement('label');
		label.textContent = "Ссылка на изображение";
        
        // create separator
		var separator = document.createElement('hr');

        // br
		var br = document.createElement('br');

		//Hide the image before adding to the DOM
		$(img).hide();
		//imgDiv.appendChild(label);
		//imgDiv.appendChild(input);
		imgDiv.appendChild(br);
		imgDiv.appendChild(img);
		imgDiv.appendChild(separator);

		//Now fade the image in
		$(img).fadeIn(300, null);
	}

</script>


  <!-- TinyMCE Script Reference -->
    <script src="~/scripts/tinymce/tinymce.min.js"></script>
    <!-- Script to wire up your TinyMCE editor -->
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea",
            theme: "modern",
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar1: "insertfile undo redo | styleselect | forecolor backcolor emoticons | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent",
            toolbar2: "link image media pagebreak | preview ",
            image_advtab: true,
            default_link_target: "_blank"
            //,
            //templates: [
            //    { title: 'Test template 1', content: 'Test 1' },
            //    { title: 'Test template 2', content: 'Test 2' }
            //]
        });
    </script>


  <!--http://www.codeproject.com/Articles/830925/Integrating-TinyMCE-into-an-MVC-Project -->

PascalWeb/Views/BlogRecord/Details.cshtml
@model PascalWeb.DB.PageModels.BlogRecordModel

    @Html.Partial("_HeadNavigation", 3)

    @Styles.Render("~/Content/RoxieTheme/css/style-custom-blog.css") 
    @Styles.Render("~/Content/RoxieTheme/css/style-custom-articles.css") 
    @Styles.Render("~/Content/RoxieTheme/css/style-custom-comment.css") 

<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('pjax:success', function (event, data, status, xhr, options) {
            document.body.scrollTop = document.documentElement.scrollTop = 0;
         //   alert(window.location);
       //     window.location.hash = '#_userCommentBox';
        });
    })
</script>

@*<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('pjax:success', function (event, data, status, xhr, options) {
         //   alert(window.location);
       //     window.location.hash = '#_userCommentBox';
        });
    })
</script>*@

<script type="text/javascript">
    //$(document).on('pjax:success', function (event, data, status, xhr, options) {
    //    //alert(window.location.hash);


    ////    alert(hash);
    //   // if (window.location.hash != "")

    //       // window.location.hash = '#_userCommentBox';
        
    //  //  history.back(1);

    //    //$('html, body').animate({
    //    //    scrollTop: $('#_userCommentBox').offset().top
    //    //}, 1000);


    //    //alert('sd');

    //    //$(window).scroll(0);

    //    //// run "custom_success" method passed to PJAX if it exists
    //    //if (typeof options.custom_success === 'function') {
    //    //    options.custom_success();
    //    //}
    //});


</script>

@if(Model != null){
    ViewBag.SocialInfo = "Блог " + Model.BlogRecord.Blog.Name;
    @Html.Partial("_PageTittle", GeneralMethods.concatenateStrings("PascalFM", " - ", Model.BlogRecord.Title))

    string creationDateStr = GeneralMethods.getFormatedDate(Model.BlogRecord.CreationDate);    

    
     <!-- CONTENT -->
    <div class="l-content">
        <div class="container b-blogs">
            <div class="">
                <section class="b-news b-news_blog" >
                    <article class="">  @*class="b-news__item"*@
                        <div class="b-news__item__head">
                            <span class="b-news__item__head__date">@creationDateStr</span>
                           @* <a href="#" title="" class="b-news__item__head__comment"  onClick="window.location.hash = '_userCommentBox'">@Model.BlogRecord.CommentsCounter.ToString()</a>*@
                            <span class="b-news__item__head__comment" >@Model.BlogRecord.CommentsCounter.ToString()</span>
                            <span class="b-news__item__head__count-watch">@Model.BlogRecord.ViewedCounter.ToString()</span>
                            @Html.ActionLink(@Model.BlogRecord.Blog.Name, "Index", "BlogRecord", new { blogID = @Model.BlogRecord.Blog.ID }, htmlAttributes: new { @class = "b-news__item__head__title", withpjax = "withpjax" })
                        </div>
                        <div class="b-news__item__wrap">
                            <div class="display: inline-block;" >
                                <span class="b-news__item__title-cat">@Model.BlogRecord.Title</span>
                            </div>
                            <br />
                            <span class="b-news__item__desrc">
                                @Html.Raw(@Model.BlogRecord.Note)
                            </span>
                        </div>
                        <div class="b-news__item__foot b-news__item__foot_mtb">
                            <div class="b-news__item__foot__social pull-right">
                                <script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script>
                                <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="small" data-yashareQuickServices="vkontakte,facebook" data-yashareTheme="counter"></div>

@*                                <a onclick="Share.vkontakte('PascalFM.ru','Pascal FM Программа','www.google.it/images/nav_logo195.png','Подробно')"> {шарь меня полностью}</a>*@

                            </div>
                            <div class="b-hashtags">
                                @{
                                    var tagList = PascalWeb.Controllers.TagController.stringToTagList(Model.BlogRecord.TagString);
                                    
                                    for (int i = 0; i < tagList.Count; i++)
                                    {
                                        <span>@Html.ActionLink(tagList[i], "Search", "Search", routeValues: new { query = "#" + tagList[i] },
                                            htmlAttributes: new { @class = "b-news__item__foot__item", withpjax = "withpjax" })</span>
                                    }
                                }
                            </div>
                        </div>
                    </article>
                </section>

                <div id="_userCommentBox">
                    @Html.Partial("..//ProgramEdition//_ViewCommentBox", Model.Comments)
                </div>
            </div>
        </div>
    </div>
}

PascalWeb/Views/BlogRecord/News.cshtml
@model PascalWeb.DB.PageModels.AdminBlogPageModel    


@Html.Partial("_PageTittle", "PascalFM - Новости")
@Html.Partial("_HeadNavigation", 3)

@Styles.Render("~/Content/RoxieTheme/css/style-custom-news.css")
@Styles.Render("~/Content/RoxieTheme/css/style-custom-articles.css")


<!-- CONTENT -->
<div class="l-content">
    <div class="container">
        <h1 class="b-title-h1 b-title-h1_news b-title-h1_fs22">новости</h1>
        @{
            Html.RenderPartial("_blogRecordListWithPagination", Model);
        } 
    </div>
</div>

PascalWeb/Views/BlogRecord/_blogRecordList.cshtml
@model List<PascalWeb.DB.BlogRecord>

    @for (int i = 0; i < Model.Count; i++)
    {
        Html.RenderPartial("..//BlogRecord//_blogRecordListElement", Model[i]);
    }               
                    

PascalWeb/Views/BlogRecord/_blogRecordListElement.cshtml
@model PascalWeb.DB.BlogRecord

@{
    var blogTagList = PascalWeb.Controllers.TagController.stringToTagList(Model.TagString);
    
    string formatDate = GeneralMethods.getFormatedDateAndTime(Model.CreationDate);
    <article class="b-news__item" style="background-color:white">
        <div class="b-news__item__head">
            <span class="b-news__item__head__date">@formatDate</span>
@*            <a href="#" title="" class="b-news__item__head__title">@Model.Blog.Name</a>*@
            @Html.ActionLink(Model.Blog.Name, "Index", "BlogRecord", new { blogID = Model.BlogID}, htmlAttributes: new { @class = "b-news__item__head__title", withpjax = "withpjax" })
        </div>
        <a href="#" title="" class="b-news__item__link">
            <span>@Html.ActionLink(Model.Title, "Details", "BlogRecord", routeValues: new { id = Model.ID },
                    htmlAttributes: new { @class = "b-news__item__title", withpjax = "withpjax" })</span>
            <span class="b-news__item__desrc">
                 @Html.Raw(@Model.NoteFragment)
            </span>

            @*читать далее*@
            @if(Model.Note != Model.NoteFragment){
                <span class="b-news__item__desrc" style="text-align:center">
                    @Html.ActionLink("читать далее", "Details", "BlogRecord", routeValues: new { id = Model.ID }, htmlAttributes: new { @class = "b-main_color", @style="text-decoration: underline;", withpjax = "withpjax" })
                </span>
            }
        </a>
        <div class="b-news__item__foot">
            <span>@Html.ActionLink(Model.CommentsCounter.ToString(), "Details", "BlogRecord", null, null, "_userCommentBox", routeValues: new { id = Model.ID },
                htmlAttributes: new { @class = "b-news__item__head__comment", @style="margin-right:20px", withpjax = "withpjax" })</span>

        @{    
            for(int i=0; i<blogTagList.Count; i++)
            {
                <span>@Html.ActionLink(blogTagList[i], "Search", "Search", routeValues: new { query = "#" + blogTagList[i] },
                    htmlAttributes: new { @class = "b-news__item__foot__item", withpjax = "withpjax" })</span>
            }
        }
        </div>
    </article>
    
}